# Gauge Java runner ayarları
gauge_custom_build_path = target/test-classes
gauge_additional_libs = target/gauge-libs/*, libs/*
gauge_clear_state_level = scenario
gauge_jvm_args = -Dfile.encoding=UTF-8, -Dstdout.encoding=UTF-8, -Dstderr.encoding=UTF-8
